// <auto-generated />
using System;
using ECommerce.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Infrastructure.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20260903140620_SeedCatalogData")]
    partial class SeedCatalogData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Domain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Description = "Electronic devices and accessories",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Clothing and fashion products",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Books and learning materials",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Products for home and kitchen",
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Sports and fitness products",
                            Name = "Sports"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            Quantity = 25,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            Quantity = 15,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            Quantity = 3,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 6,
                            Quantity = 20,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 7,
                            Quantity = 30,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 8,
                            Quantity = 18,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 9,
                            Quantity = 12,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 10,
                            Quantity = 10,
                            ReorderLevel = 3
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 11,
                            Quantity = 8,
                            ReorderLevel = 3
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 12,
                            Quantity = 6,
                            ReorderLevel = 3
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 13,
                            Quantity = 7,
                            ReorderLevel = 3
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 14,
                            Quantity = 20,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 15,
                            Quantity = 9,
                            ReorderLevel = 3
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 16,
                            Quantity = 1,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 17,
                            Quantity = 14,
                            ReorderLevel = 5
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Bluetooth over-ear wireless headphones",
                            IsActive = true,
                            Name = "Wireless Headphones",
                            Price = 2499.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Fitness tracking smart watch",
                            IsActive = true,
                            Name = "Smart Watch",
                            Price = 3999.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "RGB mechanical keyboard for computers",
                            IsActive = true,
                            Name = "Mechanical Keyboard",
                            Price = 2999.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Ergonomic wireless mouse",
                            IsActive = true,
                            Name = "Wireless Mouse",
                            Price = 1299.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Comfortable regular-fit cotton T-shirt",
                            IsActive = true,
                            Name = "Cotton T-Shirt",
                            Price = 799.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Classic slim-fit denim jeans",
                            IsActive = true,
                            Name = "Slim Fit Jeans",
                            Price = 1799.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "Lightweight running shoes",
                            IsActive = true,
                            Name = "Running Shoes",
                            Price = 2499.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Description = "A practical guide to writing clean software",
                            IsActive = true,
                            Name = "Clean Code",
                            Price = 699.00m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            Description = "Programming fundamentals and C# concepts",
                            IsActive = true,
                            Name = "C# Programming Guide",
                            Price = 899.00m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            Description = "Guide to building modern web applications",
                            IsActive = true,
                            Name = "ASP.NET Core Development",
                            Price = 1099.00m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 6,
                            Description = "Automatic coffee maker for home",
                            IsActive = true,
                            Name = "Coffee Maker",
                            Price = 3499.00m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 6,
                            Description = "Insulated stainless steel water bottle",
                            IsActive = true,
                            Name = "Stainless Steel Water Bottle",
                            Price = 899.00m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 6,
                            Description = "Reusable containers for kitchen storage",
                            IsActive = true,
                            Name = "Kitchen Storage Set",
                            Price = 1299.00m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 7,
                            Description = "Non-slip exercise and yoga mat",
                            IsActive = true,
                            Name = "Yoga Mat",
                            Price = 999.00m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 7,
                            Description = "Durable backpack for gym and sports",
                            IsActive = true,
                            Name = "Gym Backpack",
                            Price = 1599.00m
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "somidiAdmin@gmail.com",
                            FullName = "System Administrator",
                            PasswordHash = "$2a$11$dHvhpXMc1FlBXhifuzTWWu9e9eF3uHqbmkDrkW1h4HCDinIK/L4CO",
                            Role = 2
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Cart", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("ECommerce.Domain.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Inventory", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("ECommerce.Domain.Entities.Inventory", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Order", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Payment", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("ECommerce.Domain.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Product", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Product", b =>
                {
                    b.Navigation("Inventory")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
